name: oblt-aws-auth
description: Grant pipelines access to AWS resources using Workload Identity Federation
author: https://github.com/elastic
public: true
requirements:
  - curl
  - jq
  - bash
  - buildkite-agent
configuration:
  properties:
    duration:
      type: number
    aws-account-id:
      type: number
  additionalProperties: false
